url: http://127.0.0.1:13000/
port: 13000

db:
  host: db
  port: 5432
  db: misskey
  user: example-misskey-user
  pass: example-misskey-pass

redis:
  host: redis
  port: 6379

id: 'aid'

disableHsts: true

